### ISSUE TITLE
Feature request: customization of force graph

### ISSUE THREAD

**Issue by Spartano** [neo4j-contrib/neovis.js#19]
Hi, it would be awesome if we could customize a bit more the look of the graph, like the strength of the force link, etc.

**Comment by mabergerx** [comment]
Is there any work done or are there any plans for this? Right now the springinnes of the force connections really make it difficult to create a user friendly graph.

**Comment by davidsbatista** [comment]
did anyone ever found a solution on how to customize the graph force? is there something like a `defaults_config.js` where one can specify default config variables and is then read by `neovis.js`?

**Comment by thebestnom** [comment]
Im currently working on merging neovis configuration with vis, in a week it should be done, still thinking about best way the api should look (im thinking about somthing like ```js
{
   Vis: {//vis config to be merged
  }
  Neoconfig: {//neo4j driver config to be merged
  }
  //Other neovis configs
}
```
)

**Comment by davidsbatista** [comment]
@thebestnom I think that's a perfect first-iteration solution just to be able to control some visualization aspects.

example: I'm trying now to have the nodes more distant from each other, and, it seems to me that the only way to control it is to: clone `neovis.js` change the `src/defaults.js` and make a build generating a new min `neo4j.js` and use it on your project - if you know about another easier solution please do let me know :)

**Comment by thebestnom** [comment]
Yeah... Thats currently the only way, one of the main reason I took over this repo, to make it more general purpose library 😄

**Comment by davidsbatista** [comment]
The approach I described above seems not work, for some reason. This is what I'm doing:

1 -  change something on `src/defaults.js`, e.g:
```
nodes: {
        shape: 'triangle',
```
2 - save and build: `npm run build` 
3 - cp `dist/neovis.js` PATH_TO_MY_PROJECT use it in <scrip> tag in the HTML

But I don't see any changes being reflected, I always get the same exact appearance

Any ideas why this might be?

**Comment by thebestnom** [comment]
We actually ignore defailt.js for the most part, the actulat config is in neovis.js in the code 😅

**Comment by thebestnom** [comment]
actully had time to finish it today, want me to publish it as alpha and test that? (doc wans't updated but `.d.ts` was so you can use that as refernce)

**Comment by thebestnom** [comment]
published 2.0.0-alpha.0 if you wanna check 😄

**Comment by davidsbatista** [comment]
Hi! thanks for you feedback! I can give it a try, it's just a matter to switch branch? Do you have any example on how to use it? or it will already use the default config file?

**Comment by thebestnom** [comment]
Just do `npn i neovis.js@2.0.0-alpha.0` instead of how you install it currently, if you're using cdn Ill test to see how to use it, if you are cloning this repo you can just change branch,...
Ill send an example in a hour

**Comment by thebestnom** [comment]
Yeah, sorry to migrate pu anything neo4j driver related (not database name and not the initial cypher) inside neo4j, and now put vis configuration inside vis, it should loom somthing like that

```js
new NeoVis({
// Normal neovis config
neo4j: {
   //Usrtname
  //Password
  //Insecure
},
visConfig: {
   // Full vis-network config you want to override
   // Can be found here: https://visjs.github.io/vis-network/docs/network/
}
}
```

**Comment by davidsbatista** [comment]
Hi, only now I had time to go through this again, so this was the steps I followed:

```
git clone git@github.com:neo4j-contrib/neovis.js.git
git checkout 2.0.0-alpha.0
npm run build
```
then I copied the generated `dist/neovis.js` into  my own web folder where I use it and, on the same folder I added a `
default.js` with a custome configuration.

I load the web page and I get this error (on the console):

`Uncaught TypeError: Bolt URL expected to be string but was: undefined`


It seems the configuration file is not being read, is the filename correct? where should I put it?

Thanks!

**Comment by thebestnom** [comment]
Ill try to send you ome tomorrow, but in the meantime I suggest that you look at the index.d.ts file, it's the exact type of the config

**Comment by davidsbatista** [comment]
OK, I will wait for a more detailed example; Sorry, I'm not a Typescript/Node/Javascript guy at all - without any more guidelines I can only go around and try for myself until I get something running, some more detailed instructions would be much appreciated :) 

Thanks for your time!

**Comment by thebestnom** [comment]
Ok, I pushed working example to `example` branch, advance-example there working with the current version and I added csv with the data I used (it's duplicated data of 2 nodes and 4 relationships)  https://github.com/neo4j-contrib/neovis.js/blob/example/examples/advanced-example.html

**Comment by davidsbatista** [comment]
I can't still get it to work, all the steps once again:

- branch: `2.0.0-alpha.0` branch
- run `npm run build-dev`
- run `cp dist/neovis* PATH_TO_MY/app/static/vendor/neovis/`

my draw() function inside the html looks like this:

```
    function draw() {
        var config = {
            container_id: "viz",
            server_url: 'bolt://localhost:7687',
            server_user: "neo4j",
            server_password: "s3cr3t",
            arrows: true,

            hierarchical: false,

            visConfig: {
                nodes: {
                    shape: 'square'
                }
            },
            labels: {
                "Person": {
                    caption: "name",
                    size: "pagerank",
                    //community: "community"
                }
            },

            relationships: {
                "ACUSA": {
                    caption: true,
                    thickness: "freq",
                },
                "APOIA": {
                    caption: true,
                    thickness: "freq",
                }
            },
            initial_cypher: "MATCH (n)-[r:ACUSA|APOIA]->(m) WHERE r.freq > 5 RETURN n,r,m"
        }
    
        viz = new NeoVis.default(config);
        viz.render();
        //console.log(viz);
    };
```

**Comment by thebestnom** [comment]
Yes sorry for the late response, I moved ```js
server_url: 'bolt://localhost:7687',
            server_user: "neo4j",
            server_password: "s3cr3t",
```
To inside neo4j, you can see that in the example

**Comment by thebestnom** [comment]
2.x now allows that
